### ISSUE TITLE
instruction.

### ISSUE THREAD

**Issue by sinisa1982** [shtirlitsDva/Revit-PCF-Exporter#34]
Hello,

Is it possible to get more detailed instruction how to install this plug in.

Best Regards

**Comment by mpmjr7** [comment]
The instructions are on the main page. Be sure to copy the .addin file, the app dll, and the two Nuget dll's to the Revit add-in folder.

**Comment by shtirlitsDva** [comment]
Wow, I didn't even know I had an issue open until today.

Well, more detailed instructions are not something I am planning to do. I understand that for ordinary users this might be very obscure. I know because it was for me before I started to learn add-in coding two years ago. Unfortunately, it is not on my drawing board.

Please try to do as best you can with the help from google and otherwise post here with specific questions.
